language: dart
dart: stable
sudo: false
#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -y imagemagick
script: "dart build_script.dart"
install:
 - bash install-pngquant.sh
cache:
  directorie:
   - $HOME/pngquant
addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
addons:
  apt:
    packages:
    - imagemagick
    - sox libsox-fmt-mp3