language: dart
dart: stable
sudo: false
env:
  global:
#  - CXX=clang++
#  - CC=clang
#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -y imagemagick
script:
 - "dart build_script.dart"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
 - bash install-dartium.sh stable latest linux-x64
 - export PATH=$PATH:$HOME/dartium
 - export DARTIUM_BIN=$HOME/dartium/dartium
 - pip install --user awscli
 - bash install-pngquant.sh
 - export PATH=$PATH:$HOME/pngquant-2.5.0/bin
# - bash install-woff2.sh
# - export PATH=$PATH:$TRAVIS_BUILD_DIR/woff2
# - cabal install webify
 - wget http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
 - unzip chromedriver_linux64.zip
 - export PATH=$PATH:$PWD
 - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar
 - java -jar selenium-server-standalone-2.39.0.jar -port 4444
cache:
  directories:
   - $HOME/pngquant-2.5.0
   - $TRAVIS_BUILD_DIR/ttf2woff
addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - imagemagick
    - sox
    - libsox-fmt-all
    - ffmpeg
    - optipng
    - fontforge
    - chromium-browser
    - google-chrome-stable
#    - g++-4.8

#TODO(xha): reste
# webify (ou utiliser ttf2woff mais alors il faut aussi rajouter une version windows)
# zopflipng
# texturepacker
