language: dart
dart: stable
sudo: false
#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -y imagemagick
script: "dart build_script.dart"
install:
 - bash install-pngquant.sh
 - export PATH=$PATH:$HOME/pngquant-2.5.0/bin
 - bash install-ttf2woff.sh
 - export PATH=$PATH:$TRAVIS_BUILD_DIR/ttf2woff-0.12
 - bash install-woff2.sh
 - export PATH=$PATH:$TRAVIS_BUILD_DIR/woff2
cache:
  directories:
   - $HOME/pngquant-2.5.0
   - $HOME/ttf2woff
addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
addons:
  apt:
    packages:
    - imagemagick
    - sox
    - libsox-fmt-all
    - ffmpeg